# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Tail-App
version:      v0.0.3
version_from: App.pm
installdirs:  site
requires:
    File::Tail:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
