#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Tail-App
version:      v0.0.1
version_from: App.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
